"""
Report Generator — AI-powered pentest report creation

Takes scan findings and generates professional markdown/HTML reports
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates professional pentest reports using AI."""

    def __init__(self, orchestrator, template_dir: Optional[str] = None):
        self.orchestrator = orchestrator
        self.template_dir = Path(template_dir) if template_dir else None

    async def generate(
        self,
        target: str,
        findings: list[dict],
        output_path: str,
        format: str = "markdown",
    ) -> str:
        """Generate a pentest report."""
        logger.info(f"Generating report for {target} ({len(findings)} findings)")

        from ..core.orchestrator import TaskType

        # Build comprehensive context
        context = self._build_context(target, findings)

        response = await self.orchestrator.route_task(
            TaskType.REPORT_GENERATION,
            self._build_report_prompt(target, findings, format),
            context=context,
        )

        report = response.content

        # Add header
        header = self._generate_header(target, len(findings))
        report = header + "\n\n" + report

        # Add AI usage footer
        footer = f"\n\n---\n*Report generated by OmniSec AI using {response.model}*"
        report += footer

        # Save
        output = Path(output_path)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(report)

        logger.info(f"Report saved to {output_path}")
        return report

    def _build_context(self, target: str, findings: list[dict]) -> dict:
        """Build context for report generation."""
        severity_counts = {}
        for f in findings:
            sev = f.get("severity", "info")
            severity_counts[sev] = severity_counts.get(sev, 0) + 1

        return {
            "target": target,
            "findings_count": len(findings),
            "severity_distribution": severity_counts,
            "scan_date": datetime.now().isoformat(),
        }

    def _build_report_prompt(self, target: str, findings: list[dict], format: str) -> str:
        """Build prompt for report generation."""
        return f"""Generate a professional penetration testing report for {target}.

Findings ({len(findings)} total):
{json.dumps(findings, indent=2, default=str)[:8000]}

Report Structure:
1. Executive Summary (non-technical overview for management)
2. Scope & Methodology
3. Risk Assessment (with severity matrix)
4. Detailed Findings (each with: description, impact, evidence, remediation, CVSS)
5. Recommendations (prioritized)
6. Appendix (raw data, tools used)

Format: {format}
Style: Professional, clear, actionable
Severity levels: Critical > High > Medium > Low > Info"""

    def _generate_header(self, target: str, findings_count: int) -> str:
        """Generate report header."""
        return f"""# 🛡️ Penetration Test Report

| Field | Value |
|-------|-------|
| **Target** | {target} |
| **Date** | {datetime.now():%Y-%m-%d %H:%M} |
| **Findings** | {findings_count} |
| **Tool** | OmniSec AI v0.1.0 |
| **Classification** | Confidential |
"""
